- .byebug_history
- Gemfile
- Gemfile.lock
- app/controllers/categories_controller.rb
- app/controllers/socks_controller.rb
- app/models/category.rb
- app/models/size.rb
- app/models/sock.rb
- app/models/style.rb
- app/views/categories/show.html.erb
- app/views/socks/index.html.erb
- config/routes.rb
- db/migrate/20160606234828_create_styles.rb
- db/migrate/20160606234944_create_categories.rb
- db/migrate/20160606235106_create_sizes.rb
- db/migrate/20160606235350_create_socks.rb
- db/schema.rb
- spec/features/visitor_browses_items_by_category_spec.rb
- spec/features/visitor_can_view_all_socks_spec.rb
- spec/models/category_spec.rb
- spec/models/size_spec.rb
- spec/models/sock_spec.rb
- spec/models/style_spec.rb
- spec/rails_helper.rb
- spec/support/factories.rb
- spec/support/factory_girl.rb
A visitor can browse socks by a specific category by using a title of a
category and visiting /:category_title. This will take them to the
categories show page. Users can view all socks.
> Browsing items by category and viewing items

- db/schema_file.xml
Schema file added containing XML from schema designer.
> added schema file

- db/seeds.rb
create categories seed data
create sizes seed data
create styles seed data
create socks seed data
four of each
> create seed data closes #5

- app/views/socks/index.html.erb
- spec/features/visitor_browses_items_by_category_spec.rb
- spec/features/visitor_can_view_all_socks_spec.rb
Add foot and image URL to feature test visitor views all socks.
Add foot and image URL to view socks/index.
> Add image path and foot

- app/views/navigations/show.html.erb
- db/seeds.rb
ready for switch to new branch
> start updating views

- .gitignore
- app/assets/javascripts/bootstrap.js
- app/assets/stylesheets/bootstrap.css
- app/controllers/navigations_controller.rb
- app/views/navigations/show.html.erb
- app/views/socks/index.html.erb
- spec/features/visitor_browses_items_by_category_spec.rb
- spec/features/visitor_browses_items_by_style_spec.rb
update socks index view
update navigation show view
add functionality to read in images
create div classes for individual socks
resize all images
space into grids
update tests for images
> update views for iteration 1 closes #2, closes #16

- app/views/layouts/application.html.erb
Add nav bar for accessibility for client. Nav bar
displays categories and styles dropdown as well as
a link to all socks and a brand name on the nav bar.
All work done within the application file in layouts.
> add nav bar

- app/models/category.rb
- app/models/size.rb
- app/models/sock.rb
- app/models/style.rb
- spec/models/category_spec.rb
- spec/models/size_spec.rb
- spec/models/sock_spec.rb
- spec/models/style_spec.rb
Model level tests and validations added for categories
size, and style.
> add validations for models

- spec/features/visitor_adds_item_to_cart_spec.rb
- spec/features/visitor_can_adjust_quantity_of_an_item_in_cart_spec.rb
- spec/features/visitor_can_create_account_and_continue_to_check_out_spec.rb
- spec/features/visitor_can_create_account_and_get_to_their_dashboard_spec.rb
- spec/features/visitor_on_root_page_can_login_or_create_account_spec.rb
- spec/features/visitor_removes_item_from_their_cart_spec.rb
add visitor test so that a visitor can add a sock
to their cart and navigate to that cart to see what
they should see.
> Add visitor feature tests

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
- config/routes.rb
- db/migrate/20160608013947_create_user.rb
- db/migrate/20160608014306_addpasswordconfirmationto_users.rb
- db/schema.rb
- spec/features/user_login_and_logout_spec.rb
- spec/features/visitor_adds_item_to_cart_spec.rb
- spec/features/visitor_can_adjust_quantity_of_an_item_in_cart_spec.rb
- spec/features/visitor_can_create_account_and_continue_to_check_out_spec.rb
- spec/features/visitor_can_create_account_and_get_to_their_dashboard_spec.rb
- spec/features/visitor_on_root_page_can_login_or_create_account_spec.rb
- spec/features/visitor_removes_item_from_their_cart_spec.rb
the first commit has the bulk of the work and I closed my commit message early, by accident.  Please see the comment I left on that commit for more details.
> Login logout create account

- spec/features/user_login_and_logout_spec.rb
- spec/models/sock_spec.rb
- spec/models/user_spec.rb
add user model validation tests
fix hound requests
> add user model test

- .byebug_history
- app/controllers/cart_socks_controller.rb
- app/controllers/socks_controller.rb
- app/views/socks/show.html.erb
- config/routes.rb
- spec/features/visitor_adds_item_to_cart_spec.rb
create cart_socks controller and routes
add show cart view
work on visitor adds item to cart spec
> start implementing adding items to cart

- app/assets/stylesheets/custom.css
- app/controllers/cart_socks_controller.rb
- app/models/cart.rb
- app/views/cart_socks/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/features/visitor_removes_item_from_their_cart_spec.rb
- spec/models/cart_spec.rb
- spec/rails_helper.rb
pass remove item test
add destroy method to cart sock controller
add remove button to views
> closes #22 add remove sock functionality to cart

- app/controllers/cart_socks_controller.rb
- app/models/cart.rb
- app/views/cart_socks/show.html.erb
- config/routes.rb
- spec/features/visitor_can_adjust_quantity_of_an_item_in_cart_spec.rb
- spec/models/cart_spec.rb
- spec/rails_helper.rb
Add method to increase quantities
Add method to decrease quantities
Add update method to cart socks controller
Get feature test to pass and update to buttons
> Closes #23 Add ability to adjust quantities in cart

- .byebug_history
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/custom.css
- app/controllers/application_controller.rb
- app/controllers/cart_socks_controller.rb
- app/controllers/socks_controller.rb
- app/models/cart.rb
- app/views/cart_socks/show.html.erb
- app/views/layouts/application.html.erb
- app/views/socks/show.html.erb
- config/routes.rb
- spec/features/visitor_adds_item_to_cart_spec.rb
- spec/features/visitor_can_adjust_quantity_of_an_item_in_cart_spec.rb
- spec/features/visitor_removes_item_from_their_cart_spec.rb
- spec/models/cart_spec.rb
- spec/rails_helper.rb
- spec/support/factories.rb
Cart functionality complete
add/remove items
adjust quantity
total price
total quantity
display each item in cart
> Iteration2 cart development

- app/controllers/home_controller.rb
- app/controllers/orders_controller.rb
- app/models/user.rb
- app/views/orders/index.html.erb
- config/routes.rb
- spec/features/logged_in_user_views_past_orders_spec.rb
- spec/features/visitor_can_create_account_and_get_to_their_dashboard_spec.rb
- spec/features/visitor_on_root_page_can_login_or_create_account_spec.rb
- spec/rails_helper.rb
- spec/support/factories.rb
User can now visit the orders path within
their session and see all of their past orders.
> closes #25 closes #26 closes #23 Add orders path

- .byebug_history
- app/controllers/home_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/models/order_item.rb
- app/models/user.rb
- app/views/cart_socks/show.html.erb
- app/views/orders/index.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20160609001024_create_orders.rb
- db/migrate/20160609001213_create_order_items.rb
- db/schema.rb
- spec/factories/order_items.rb
- spec/factories/orders.rb
- spec/features/logged_in_user_views_past_orders_spec.rb
- spec/features/visitor_can_create_account_and_continue_to_check_out_spec.rb
- spec/features/visitor_can_create_account_and_get_to_their_dashboard_spec.rb
- spec/features/visitor_on_root_page_can_login_or_create_account_spec.rb
- spec/models/order_item_spec.rb
- spec/models/order_spec.rb
- spec/rails_helper.rb
- spec/support/factories.rb
With this branch we add the ability of a user to view their past orders as well as visit their dashboard.
> Finishing Iteration 2 Functionality, Order development

- app/controllers/cart_socks_controller.rb
- spec/models/cart_spec.rb
- spec/models/order_item_spec.rb
- spec/models/order_spec.rb
Add edge case testing for model level tests
for the cart.
> closes #44 add model testing

- app/views/navigations/show.html.erb
- app/views/socks/index.html.erb
- spec/features/visitor_browses_items_by_category_spec.rb
- spec/features/visitor_browses_items_by_style_spec.rb
- spec/features/visitor_can_view_all_socks_spec.rb
Add sock show page links to styles index
Add sock show page links to categories index
Add sock show page links to socks index
update feature tests to reflect links' existence
> Closes #48 Add sock show page links to styles, categories, socks index

- .byebug_history
- app/controllers/users_controller.rb
- app/models/user.rb
- db/seeds.rb
- spec/features/visitor_can_create_account_and_get_to_their_dashboard_spec.rb
password confirmation added to user_params in user controller
password confirmations working properly for account creation
need to fix failed login redirection route
test written
> Fix password confirmation

- .byebug_history
- app/controllers/admin/base_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/admin/users/show.html.erb
- app/views/users/edit.html.erb
- config/routes.rb
- spec/factories/order_items.rb
- spec/features/admin_can_only_modify_own_data_spec.rb
- spec/features/admin_login_dashboard_spec.rb
- spec/features/user_only_sees_their_own_information_spec.rb
- spec/features/visitor_can_create_account_and_get_to_their_dashboard_spec.rb
- spec/support/factories.rb
Closes #65 Closes #66 Closes #67 Closes #68 Closes #69
> Authorization development

- app/controllers/orders_controller.rb
- app/models/order.rb
- app/models/sock.rb
- app/views/orders/show.html.erb
- db/migrate/20160611170315_add_status_to_orders.rb
- db/schema.rb
- spec/features/user_can_view_individual_orders_spec.rb
Add migration to add status column
Update order show page to show attributes of individual order
Add total methods to find total quantity and total price in order model
> Closes #62 View individual order information on that order's show page

- app/controllers/orders_controller.rb
- app/controllers/sessions_controller.rb
- app/models/cart.rb
- app/models/order.rb
- app/views/cart_socks/show.html.erb
- config/routes.rb
- spec/features/user_can_checkout_spec.rb
- spec/features/visitor_can_create_account_and_continue_to_check_out_spec.rb
- spec/models/cart_spec.rb
- spec/models/order_spec.rb
Add model test for creation of order items from cart contents
Add feature test for creation of order
Add ability to checkout if logged in
Add functionality so that when checking out cart is created as new order
And cart contents become order items
> Closes #64 Checkout functionality

- app/views/socks/show.html.erb
- db/migrate/20160611203433_add_retired_to_socks.rb
- db/schema.rb
- spec/features/items_can_be_retired_spec.rb
Add feature test to ensure user cannot add retired item to cart
> Closes #63 Add functionality to have retired items

- app/controllers/orders_controller.rb
- app/controllers/sessions_controller.rb
- spec/features/user_can_checkout_spec.rb
Add persistence of cart if user logs out, so cart persists even if logged out
Add persistence of user once order placed, so that user persists while cart session cleared
> Closes #80 Add deletion of items from cart when order placed

- app/views/charges/new.html.erb
- app/views/socks/index.html.erb
- app/views/socks/show.html.erb
updated new charge page
update sock index page
update sock show page
> update views to display properly formatted currencies
